// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkp-Ki1nsUiz3te2ce4kbDjlpBOIi_4w8',
    appId: '1:719640012398:android:521bece77c2e39a5b2287f',
    messagingSenderId: '719640012398',
    projectId: 'logictech-esports',
    storageBucket: 'logictech-esports.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAL3_SHVP3WIf7ROmVTDLCzdrzj2SlFPQ',
    appId: '1:719640012398:ios:71d23e23e2e374d1b2287f',
    messagingSenderId: '719640012398',
    projectId: 'logictech-esports',
    storageBucket: 'logictech-esports.appspot.com',
    androidClientId: '719640012398-s5ullg8vcr7e2000eqmk03i3hpe8gmn6.apps.googleusercontent.com',
    iosClientId: '719640012398-vjprmvsfv1bmf5diimkc28o811rbqjk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.logictechEsports',
  );
}
